In [1]:
num_1 = 4
num_2 = 2
print(num_1+num_2)
print(num_1-num_2)

6
2


In [3]:
tupla_1 = (1, 2, 3)
tupla_2 = (1, 20, 3)
print(tupla_1+tupla_2)

(1, 2, 3, 1, 20, 3)


In [4]:
tupla_1 += tupla_2
display(tupla_1)
display(tupla_2)

(1, 2, 3, 1, 20, 3)

(1, 20, 3)

In [9]:
lista_da_tupla_1 = list(tupla_1)
lista_da_tupla_1

[1, 2, 3, 1, 20, 3]

In [16]:
lista_da_tupla_1[2] += 2
lista_da_tupla_1

[1, 2, 13, 1, 20, 3]

In [13]:
dict_1 = {'a': 1, 'b': 2}
dict_2 = {'a': 1, 'b': 20}
dict_1 +dict_2

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

In [14]:
import numpy as np

In [17]:
array = np.array(lista_da_tupla_1)
array

array([ 1,  2, 13,  1, 20,  3])

In [19]:
array += 2
array

array([ 5,  6, 17,  5, 24,  7])

In [21]:
array *= array
array

array([   625,   1296,  83521,    625, 331776,   2401])

In [23]:
len(np.insert(arr=array, obj=2, values=100))

7

In [40]:
array = np.array(lista_da_tupla_1).reshape(3, 2)
array

array([[ 1,  2],
       [13,  1],
       [20,  3]])

In [41]:
import pandas as pd

In [42]:
df = pd.DataFrame(array)
df

,0,1
0,1,2
1,13,1
2,20,3


In [43]:
array_ones = np.ones_like(df)
array_ones[1,1] = 100
array_ones

array([[  1,   1],
       [  1, 100],
       [  1,   1]])

In [44]:
"py" != "py"

False

In [46]:
2 <= 3 < 7

True

In [47]:
import numpy as np
import pandas as pd