# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [8]:
a = 2.0 + 3.0 / 5.0
b = (a + 10.2) - 5.0*2.0
c = a/b + 33.8
d = a/(b + c)
e = d*2

print (a)
print (b)
print (c)
print (d)
print (e)

2.6
2.799999999999999
34.72857142857143
0.0692805481537876
0.1385610963075752


## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [9]:
lista_a = [2.0, 3.0, 5.0] + [10, 20, 30]
print (lista_a)

[2.0, 3.0, 5.0, 10, 20, 30]


In [12]:
lista_b = lista_a * 2
print (lista_b)

[2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]


In [13]:
lista_c = lista_a + lista_b
print (lista_c)

[2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]


In [14]:
lista_d = lista_a / (lista_b * lista_c)
print (lista_d)

TypeError: can't multiply sequence by non-int of type 'list'

## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [18]:
ex_3_lista1 = [a, 
               b, 
               c, 
               d, 
               e]
print (ex_3_lista1)

[2.6, 2.799999999999999, 34.72857142857143, 0.0692805481537876, 0.1385610963075752]


In [19]:
ex_3_lista2 = [x**0.5 for x in ex_3_lista1]
print (ex_3_lista2)

[1.61245154965971, 1.6733200530681507, 5.893095233285427, 0.263211983302029, 0.3722379565648501]


In [20]:
ex_3_lista3 = ex_3_lista1 + ex_3_lista2
print (ex_3_lista3)

[2.6, 2.799999999999999, 34.72857142857143, 0.0692805481537876, 0.1385610963075752, 1.61245154965971, 1.6733200530681507, 5.893095233285427, 0.263211983302029, 0.3722379565648501]


## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [22]:
import numpy as np

In [23]:
duply = ex_3_lista3 * 2
print (duply)   

[2.6, 2.799999999999999, 34.72857142857143, 0.0692805481537876, 0.1385610963075752, 1.61245154965971, 1.6733200530681507, 5.893095233285427, 0.263211983302029, 0.3722379565648501, 2.6, 2.799999999999999, 34.72857142857143, 0.0692805481537876, 0.1385610963075752, 1.61245154965971, 1.6733200530681507, 5.893095233285427, 0.263211983302029, 0.3722379565648501]


In [27]:
array_dup = np.array(duply).reshape(5, 4)
array_dup

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796]])

## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [28]:
list_mean = array_dup.mean(axis=0).tolist()
print (list_mean)

[7.8807329122498375, 2.1494130575327546, 7.8807329122498375, 2.149413057532755]


## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [30]:
array_dup.shape


(5, 4)

In [33]:
array_ex6 = np.append(array_dup, [list_mean], axis=0)
array_ex6

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796],
       [ 7.88073291,  2.14941306,  7.88073291,  2.14941306]])

## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [37]:
import pandas as pd

In [38]:
array_ex7 = array_ex6.reshape(-1, 4)
array_ex7

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796],
       [ 7.88073291,  2.14941306,  7.88073291,  2.14941306]])

In [39]:
array_ex7 = pd.DataFrame(array_ex7).round(3)
array_ex7

,0,1,2,3
0,2.600,2.800,34.729,0.069
1,0.139,1.612,1.673,5.893
2,0.263,0.372,2.600,2.800
3,34.729,0.069,0.139,1.612
4,1.673,5.893,0.263,0.372
5,7.881,2.149,7.881,2.149


## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [40]:
array_ex7['medias'] = array_ex7.mean(axis=1)
array_ex7 

,0,1,2,3,medias
0,2.600,2.800,34.729,0.069,10.04950
1,0.139,1.612,1.673,5.893,2.32925
2,0.263,0.372,2.600,2.800,1.50875
3,34.729,0.069,0.139,1.612,9.13725
4,1.673,5.893,0.263,0.372,2.05025
5,7.881,2.149,7.881,2.149,5.01500


## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [42]:
array_ex7.describe()

,0,1,2,3,medias
count,6.000000,6.000000,6.000000,6.000000,6.000000
mean,7.880833,2.149167,7.880833,2.149167,5.015000
std,13.455228,2.107787,13.455228,2.107787,3.758615
min,0.139000,0.069000,0.139000,0.069000,1.508750
25%,0.615500,0.682000,0.615500,0.682000,2.120000
50%,2.136500,1.880500,2.136500,1.880500,3.672125
75%,6.560750,2.637250,6.560750,2.637250,8.106688
max,34.729000,5.893000,34.729000,5.893000,10.049500


## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [43]:
array_ex7.columns = ['col 1', 'col 2', 'col 3', 'col 4', 'medias']
array_ex7.index = ['linha 1', 'linha 2', 'linha 3', 'linha 4', 'linha 5', 'medias']
array_ex7

,col 1,col 2,col 3,col 4,medias
linha 1,2.600,2.800,34.729,0.069,10.04950
linha 2,0.139,1.612,1.673,5.893,2.32925
linha 3,0.263,0.372,2.600,2.800,1.50875
linha 4,34.729,0.069,0.139,1.612,9.13725
linha 5,1.673,5.893,0.263,0.372,2.05025
medias,7.881,2.149,7.881,2.149,5.01500


média das médias é 5.01500

In [45]:
array_ex7.to_csv ('array_ex7.csv')