# Exercício:

## 01 – Obtenha os resultados e retorne o código Python dos seguintes cálculos:

<br>a = 2.0 + 3.0 / 5.0 == 10
<br>b = (a + 10.2) - 5.0 * 2.0 <= 2.9
<br>c = 10 <= a / b + 33.8 < 100
<br>d = 5 != a / (b + c)
<br>e = 33 == d * 2

In [3]:
a = 2.0 + 3.0 / 5.0 == 10
b = (a + 10.2) - 5.0 * 2.0 <= 2.9
c = 10 <= a / b + 33.8 < 100
d = 5 != a / (b + c)
e = 33 == d * 2

print(a, b, c, d, e)

False True True True False


## 02 – Altere os operadores relacionais para modificar o resultado de cada uma das comparações.

<br>('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>['a',1,True,'b',0,False] > ['a',True,1]
<br>['a',1,True,'b',0,False] == 1
<br>['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [6]:
print("exercicio 01:")
print(('a',1,True,'b',0,False) != ('a',True,1,'b',False,0))
print("substituindo por == resultado em:")
print(('a',1,True,'b',0,False) == ('a',True,1,'b',False,0))

print("exercicio 02:")
print(['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)) 
print("substituindo por == resultado em:")
print(['a',1,True,'b',0,False] == ('a',True,1,'b',False,0))

print("exercicio 03:")
print(['a',1,True,'b',0,False] != ['a',True,1,'b',False,0])
print("substituindo por == resultado em:")
print(['a',1,True,'b',0,False] == ['a',True,1,'b',False,0])

print("exercicio 04:")
print(['a',1,True,'b',0,False] > ['a',True,1])
print("substituindo por < resultado em:")
print(['a',1,True,'b',0,False] < ['a',True,1])

print("exercicio 05:")
print(['a',1,True,'b',0,False] == 1)
print("substituindo por != resultado em:")
print(['a',1,True,'b',0,False] != 1)

print("exercicio 06:")
print(['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False])
print("substituindo por > resultado em:")
print(['a',True,1] > ['a',True,1] < ['a',1,True,'b',0,False])



exercicio 01:
False
substituindo por == resultado em:
True
exercicio 02:
True
substituindo por == resultado em:
False
exercicio 03:
False
substituindo por == resultado em:
True
exercicio 04:
True
substituindo por < resultado em:
False
exercicio 05:
False
substituindo por != resultado em:
True
exercicio 06:
True
substituindo por > resultado em:
False


## 03 – Usando o método DataFrame.to_csv(‘nome_do_arquivo.csv’) exporte o objeto obtido no exercício 10 da aula anterior para um arquivo CSV. Usando o método pd.read_csv(‘nome_do_arquivo.csv’) instancie uma DataFrame. Use o valor ‘Unnamed: 0’ no parâmetro index_col, para ajustar o index. Arredonde os valores para até três casas decimais, usando o método round().
Recupere a DataFrame.

In [15]:

import pandas as pd
import numpy as np

In [32]:
df_ex3 = pd.read_csv('/home/nina/Documents/Aula git/Data/array_ex7.csv', index_col='Unnamed: 0')
df_ex3 = df_ex3.round(3)
df_ex3


,col 1,col 2,col 3,col 4,medias
linha 1,2.600,2.800,34.729,0.069,10.050
linha 2,0.139,1.612,1.673,5.893,2.329
linha 3,0.263,0.372,2.600,2.800,1.509
linha 4,34.729,0.069,0.139,1.612,9.137
linha 5,1.673,5.893,0.263,0.372,2.050
medias,7.881,2.149,7.881,2.149,5.015


## 04 – Instancie um numpy array que apresente o mesmo formato (linhas e colunas) da DataFrame. Este array deve conter apenas inteiros uns.
Recupere o array.

Obs.: Procure na internet o método numpy.ones()

In [33]:
array_ones = np.ones_like(df_ex3)
array_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 05 – Quantos dos valores contidos na DataFrame são iguais aos valores no array?

In [34]:
df_ex3.values == array_ones

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

R: nenhum é igual

## 06 – Quantos dos valores contidos na DataFrame são superiores aos valores no array?

In [35]:
df_ex3.values > array_ones

array([[ True,  True,  True, False,  True],
       [False,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [ True, False, False,  True,  True],
       [ True,  True, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [36]:
(df_ex3.values > array_ones).sum()

np.int64(22)

R: 22 valores são iguais.

## 07 – Quantos dos valores contidos na DataFrame são iguais ou inferiores aos valores no array?

In [37]:
df_ex3.values <= array_ones

array([[False, False, False,  True, False],
       [ True, False, False, False, False],
       [ True,  True, False, False, False],
       [False,  True,  True, False, False],
       [False, False,  True,  True, False],
       [False, False, False, False, False]])

In [39]:
(df_ex3.values <= array_ones).sum()

np.int64(8)

R: oito valores são menores ou iguais

## 08 – Quantos dos valores contidos na DataFrame estão entre 0 e 1?

In [51]:
(df_ex3.gt(0) & df_ex3.lt(1)).sum().sum()

np.int64(8)

## 09 – Quantos dos valores das médias das linhas são inferiores ou iguais à 5?

Obs 1.: Usando o método de classe, você pode converter qualquer objeto em outra classe. Ex. obj = list(array)

Obs 2.: Assim com o objeto da classe str, listas também possuem a função count()

In [52]:
df_ex3['medias']

linha 1    10.050
linha 2     2.329
linha 3     1.509
linha 4     9.137
linha 5     2.050
medias      5.015
Name: medias, dtype: float64

In [ ]:
df_ex3['medias'] <= 5

linha 1    False
linha 2     True
linha 3     True
linha 4    False
linha 5     True
medias     False
Name: medias, dtype: bool

In [56]:
(df_ex3['medias'] > 5).sum()

np.int64(3)

R: são 3 valores

## 10 – Quantos dos valores das médias das colunas são superiores à 5?

In [55]:
df_ex3['medias'] > 5

linha 1     True
linha 2    False
linha 3    False
linha 4     True
linha 5    False
medias      True
Name: medias, dtype: bool

In [57]:
(df_ex3['medias'] > 5).sum()

np.int64(3)

R: são 3 valores.